# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .acl import *
from .aws_cloud_watch_logs_integration import *
from .aws_cloud_watch_metrics_integration import *
from .get_network import *
from .get_project import *
from .integration import *
from .managed_cluster import *
from .managed_cluster_replicaset import *
from .network import *
from .peering import *
from .project import *
from .provider import *
from .scheduled_backup import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_kurrentcloud.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_kurrentcloud.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "kurrentcloud",
  "mod": "index/aWSCloudWatchLogsIntegration",
  "fqn": "pulumi_kurrentcloud",
  "classes": {
   "kurrentcloud:index/aWSCloudWatchLogsIntegration:AWSCloudWatchLogsIntegration": "AWSCloudWatchLogsIntegration"
  }
 },
 {
  "pkg": "kurrentcloud",
  "mod": "index/aWSCloudWatchMetricsIntegration",
  "fqn": "pulumi_kurrentcloud",
  "classes": {
   "kurrentcloud:index/aWSCloudWatchMetricsIntegration:AWSCloudWatchMetricsIntegration": "AWSCloudWatchMetricsIntegration"
  }
 },
 {
  "pkg": "kurrentcloud",
  "mod": "index/acl",
  "fqn": "pulumi_kurrentcloud",
  "classes": {
   "kurrentcloud:index/acl:Acl": "Acl"
  }
 },
 {
  "pkg": "kurrentcloud",
  "mod": "index/integration",
  "fqn": "pulumi_kurrentcloud",
  "classes": {
   "kurrentcloud:index/integration:Integration": "Integration"
  }
 },
 {
  "pkg": "kurrentcloud",
  "mod": "index/managedCluster",
  "fqn": "pulumi_kurrentcloud",
  "classes": {
   "kurrentcloud:index/managedCluster:ManagedCluster": "ManagedCluster"
  }
 },
 {
  "pkg": "kurrentcloud",
  "mod": "index/managedClusterReplicaset",
  "fqn": "pulumi_kurrentcloud",
  "classes": {
   "kurrentcloud:index/managedClusterReplicaset:ManagedClusterReplicaset": "ManagedClusterReplicaset"
  }
 },
 {
  "pkg": "kurrentcloud",
  "mod": "index/network",
  "fqn": "pulumi_kurrentcloud",
  "classes": {
   "kurrentcloud:index/network:Network": "Network"
  }
 },
 {
  "pkg": "kurrentcloud",
  "mod": "index/peering",
  "fqn": "pulumi_kurrentcloud",
  "classes": {
   "kurrentcloud:index/peering:Peering": "Peering"
  }
 },
 {
  "pkg": "kurrentcloud",
  "mod": "index/project",
  "fqn": "pulumi_kurrentcloud",
  "classes": {
   "kurrentcloud:index/project:Project": "Project"
  }
 },
 {
  "pkg": "kurrentcloud",
  "mod": "index/scheduledBackup",
  "fqn": "pulumi_kurrentcloud",
  "classes": {
   "kurrentcloud:index/scheduledBackup:ScheduledBackup": "ScheduledBackup"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "kurrentcloud",
  "token": "pulumi:providers:kurrentcloud",
  "fqn": "pulumi_kurrentcloud",
  "class": "Provider"
 }
]
"""
)
