// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ManagedClusterReplicaset extends pulumi.CustomResource {
    /**
     * Get an existing ManagedClusterReplicaset resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ManagedClusterReplicasetState, opts?: pulumi.CustomResourceOptions): ManagedClusterReplicaset {
        return new ManagedClusterReplicaset(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'eventstorecloud:index/managedClusterReplicaset:ManagedClusterReplicaset';

    /**
     * Returns true if the given object is an instance of ManagedClusterReplicaset.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ManagedClusterReplicaset {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ManagedClusterReplicaset.__pulumiType;
    }

    /**
     * ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
     */
    public readonly clusterId!: pulumi.Output<string>;
    /**
     * Creation timestamp
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * ID of the project that owns the parent managed cluster
     */
    public readonly projectId!: pulumi.Output<string>;
    /**
     * Protection from accidental deletion. Delete is rejected by the API while this is true.
     */
    public readonly protected!: pulumi.Output<boolean | undefined>;
    /**
     * Number of read-only replicas in the set (1 or 2)
     */
    public readonly replicaCount!: pulumi.Output<number>;
    /**
     * Current status of the read-only replica set
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * Last modification timestamp
     */
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;

    /**
     * Create a ManagedClusterReplicaset resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ManagedClusterReplicasetArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ManagedClusterReplicasetArgs | ManagedClusterReplicasetState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ManagedClusterReplicasetState | undefined;
            resourceInputs["clusterId"] = state ? state.clusterId : undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["projectId"] = state ? state.projectId : undefined;
            resourceInputs["protected"] = state ? state.protected : undefined;
            resourceInputs["replicaCount"] = state ? state.replicaCount : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
        } else {
            const args = argsOrState as ManagedClusterReplicasetArgs | undefined;
            if ((!args || args.clusterId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clusterId'");
            }
            if ((!args || args.projectId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if ((!args || args.replicaCount === undefined) && !opts.urn) {
                throw new Error("Missing required property 'replicaCount'");
            }
            resourceInputs["clusterId"] = args ? args.clusterId : undefined;
            resourceInputs["projectId"] = args ? args.projectId : undefined;
            resourceInputs["protected"] = args ? args.protected : undefined;
            resourceInputs["replicaCount"] = args ? args.replicaCount : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ManagedClusterReplicaset.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ManagedClusterReplicaset resources.
 */
export interface ManagedClusterReplicasetState {
    /**
     * ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
     */
    clusterId?: pulumi.Input<string>;
    /**
     * Creation timestamp
     */
    createdAt?: pulumi.Input<string>;
    /**
     * ID of the project that owns the parent managed cluster
     */
    projectId?: pulumi.Input<string>;
    /**
     * Protection from accidental deletion. Delete is rejected by the API while this is true.
     */
    protected?: pulumi.Input<boolean>;
    /**
     * Number of read-only replicas in the set (1 or 2)
     */
    replicaCount?: pulumi.Input<number>;
    /**
     * Current status of the read-only replica set
     */
    status?: pulumi.Input<string>;
    /**
     * Last modification timestamp
     */
    updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ManagedClusterReplicaset resource.
 */
export interface ManagedClusterReplicasetArgs {
    /**
     * ID of the parent managed cluster. Used as the resource ID since each cluster has at most one read-only replica set.
     */
    clusterId: pulumi.Input<string>;
    /**
     * ID of the project that owns the parent managed cluster
     */
    projectId: pulumi.Input<string>;
    /**
     * Protection from accidental deletion. Delete is rejected by the API while this is true.
     */
    protected?: pulumi.Input<boolean>;
    /**
     * Number of read-only replicas in the set (1 or 2)
     */
    replicaCount: pulumi.Input<number>;
}
